version: '3'
services:
  web:
    image: node:18-alpine
    container_name: web-bot
    working_dir: /var/www/
    volumes:
      - ./:/var/www/
    ports:
      - "8095:8080"
    command: npm run dev