version: '3'
services:
  web:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web-bot
    working_dir: /var/www/
    volumes:
      - ./:/var/www/
    ports:
      - "8095:8080"

